export { SuperadminUser } from './superadmin-user.entity';
export { University } from './university.entity';
export { Program } from './program.entity';
export { ProgramDepartment } from './program-department.entity';
export { ProgramSemester } from './program-semester.entity';
export { CourseType } from './course-type.entity';
export { CourseSubject } from './course-subject.entity';
export { CourseTopic } from './course-topic.entity';
export { CourseSubtopic } from './course-subtopic.entity';
